# Generated by Django 5.0.3 on 2024-04-25 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 1, 26, 32, 981998, tzinfo=datetime.timezone.utc)),
        ),
    ]
